# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration
name = "Sellora"
client_id = "7d912d414ddbffe0c1ff644b418efcf9"
application_url = "https://loops-alien-possibility-physics.trycloudflare.com/shopify"
embedded = true

[access_scopes]
scopes = "read_products,read_inventory,read_locations,write_pixels,read_customer_events,read_orders,write_products,write_discounts"

[auth]
redirect_urls = [ "https://loops-alien-possibility-physics.trycloudflare.com/auth/shopify/callback" ]

[webhooks]
api_version = "2025-10"

[[webhooks.subscriptions]]
compliance_topics = [ "customers/data_request", "customers/redact", "shop/redact" ]
uri = "/webhooks/shopify/privacy"
