# examples:
#   periodic_cleanup:
#     class: CleanSoftDeletedRecordsJob
#     queue: background
#     args: [ 1000, { batch_size: 500 } ]
#     schedule: every hour

production:
  clear_solid_queue_finished_jobs:
    command: "SolidQueue::Job.clear_finished_in_batches(sleep_between_batches: 0.3)"
    schedule: every hour at minute 12

  sellora_daily_discovery:
    class: Pilot::DailyDiscoveryJob
    queue: default
    schedule: at 2am every day

development:
  sellora_daily_discovery:
    class: Pilot::DailyDiscoveryJob
    queue: default
    schedule: every day at 2am
